walletconnect:
  relay:
    mode: legacy
  classifier: default
  service:
    type: ClusterIP
  deployment:
    image:
    tag: latest
    terminationGracePeriodSeconds: 900
    replicas: 1
    imagePullPolicy: Always
    resources:
      limits:
        memory: 2Gi
        cpu: 2
  ingress:
    enabled: false
    zone:
      domain:
    paths: []
    apiVersion: "extensions/v1beta1"
    labels: {}
    tls: true
