walletconnect:
  relay:
    mode: any
  service:
    port: 5000
  deployment:
    replicas: 1
    resources:
      limits:
        memory: 1Gi
        cpu: 1
  ingress:
    enabled: true
    zone:
      domain: example.com # Put in your domain

