walletconnect:
  service:
    port: 5000
  deployment:
    replicas: 1
    resources:
      limits:
        memory: 8Gi
        cpu: 4
  ingress:
    enabled: true
    zone:
      domain: example.com # Put in your domain
