apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-redis
spec:
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-redis
        chart: {{ $.Chart.Name }}
    spec:
      containers:
        - name: {{ template "fullname" . }}-redis
          image: redis:6-alpine
          resources:
            limits:
              memory: 512Mi
              cpu: .5

          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-redis
  annotations:
spec:
  type: ClusterIP
  selector:
    app: {{ template "fullname" . }}-redis
  ports:
    - name: {{ template "fullname" . }}-redis-port
      protocol: TCP
      port: 6379
      targetPort: 6379
